[package]
name = "test-package"
authors = ["Logan Koester <logan@logankoester.com>"]
version = "0.1.0"
homepage = "https://smaug.dev"
keywords = []

# Optional:
# documentation = "https://example.com"
# repository = "http://github.com/example/example"

# Which files do you want to be automatically required from your package.
# requires = ["lib/library.rb"]


[package.installs]
# Example
#
# <from> = <to>
# "lib/library.rb" = "app/lib/library.rb"

[dragonruby]
version = "2"
edition = "standard"
